### ISSUE TITLE
Suggestion

### ISSUE THREAD

**Issue by Bhaskar-git-oss** [axel358/smartdock#170]
- [ ] I would like you to add hide navigation bar and 
status bar button like in **smart launcher**.

- [x] Bring the ability to set custom **icon pack**.

**Comment by axel358** [comment]
Icon packs have been restored for the next version https://github.com/axel358/smartdock/issues/154. Hiding the navigation and status bars is not a standard procedure, the method varies between Android versions, these options existed in the past and were removed because they were unreliable. If u need to hide these bars there are overlays and modules you can use if u have root available

**Comment by axel358** [comment]
Icon packs have been restored for the next version https://github.com/axel358/smartdock/issues/154. Hiding the navigation and status bars is not a standard procedure, the method varies between Android versions, these options existed in the past and were removed because they were unreliable. If u need to hide these bars there are overlays and modules you can use if u have root available
